### ISSUE TITLE
Changing the iterator inside an object map

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/collection-containers-spec#10]
@frmichel proposed the ability to change the iterator inside a term map. This would allow one to "manipulate" the "input" prior to applying the term map. A use case could be to flatten a list of values, for instance. Examples were included in the context of RML containers and collections, BUT I believe that this proposal would need to be discussed in the RML spec. What do you think?

**Comment by frmichel** [comment]
Another application is to complement what we can do with fields: fields do all the processing about needed iterations at the logical source level. Sometimes, what you need is simply a "local" iteration change, e.g., in a single object map where you will iterate locally on the values of an array. Subsequently, we could treat the result of this local iteration with e.g. a gather map.

**Comment by chrdebru** [comment]
@dachafra is there a way to move this discussion to another part of the spec? We believe this discussion should be moved to the core specification.

**Comment by dachafra** [comment]
sure! We can do it, but it is not clear to me if the core spec is this https://github.com/kg-construct/rml-fno-spec or we need to create a new one? cc @andimou

**Comment by andimou** [comment]
I think that https://github.com/kg-construct/rml-fno-spec is not the right place. 

Perhaps, we could introduce a tag for field-related discussions and include it here as well? Then we can see what needs to be done with fields, what overlaps among different modules and what strategy we follow accross modules. 

Strategy 1: We let the Gather Map have its own iterator
Stategy 2: We let the Gather Map have a default behavior and if more comlicated, then use fields.
Stategy 3: Something else?

**Comment by dachafra** [comment]
I would go for strategy 2 and move this issue to [RML-fields spec](https://github.com/kg-construct/rml-fields-spec)

**Comment by chrdebru** [comment]
Strategy 2 would keep things simple. If I understand it correctly, moving it in the fields would mean that we would declare a field where a "different view" on the document is stored for the gather map. Can declaring a new iterator for a gather map be considered as "syntactic sugar" for an "unnamed" field? I believe @frmichel should pitch in here.

**Comment by frmichel** [comment]
I guess restricting this idea of changing the iterator only within gather maps would miss the target that, I think, is much larger. I see this possibility as a feature that would apply to any kind of term map. But that means making quite a lot of changes in the core iteration model, and probably this is not a good idea to do that now.

So I propose to keep this in mind for a future version, given that for now we can do the same with fields.

I close this issue, feel free to reopen it if I missed something.

**Comment by frmichel** [comment]
I just tried to see if RML fields can replace the term map iterator. 
Long story short: no :(

Input document:
```json
{ "id": 1,
  "a" : [ [1,2,3], [4,5,6] ]
}
```
The expected output is to generate a list of lists:
```
( (1 2 3) (4 5 6) )
```

Declare a field in the logical source:
```turtle
rml:logicalSource [
  rml:source ... ;
  rml:field [ rml:name "a" ; rml:reference "$.a.*" 
];
```
This reshapes the input document into 2 documents: 
```json
{
  "id": 1, "a": [1,2,3]
}
{
  "id": 1, "a": [4,5,6]
}
```

Now if we apply the following term map:
```turtle
rr:subjectMap [ 
  rr:template "http://my.list/{$.id}";
  rml:gather ( [ rml:reference "$.a.*" ] ); 
  rml:gatherAs rdf:List;
] ;
```

This will yield:
```turtle
<http://my.list/1> rdf:first (1 2 3).
<http://my.list/1> rdf:first (4 5 6).
```
which is invalid as we want:
```turtle
<http://my.list/1> rdf:first (1 2 3); rdf:rest (4 5 6).
```

Conversely, if we endorse the use of rml:iterator within a term map (aka. term map iterator) then it can work:

```turtle
  rr:subjectMap [ 
    rr:template "http://my.list/{$.id}";
    rml:iterator "$.a";
    rml:gather (
        [ rml:gather ( [ rml:reference "$.*" ] ); 
          rml:gatherAs rdf:List; 
    ]);
    rml:gatherAs rdf:List;
  ] ;
```
Only trouble, depending on the precise semantics we define for a term map iterator, we may have to use the "access field outside iteration" pattern, to keep the id within the current iteration.

**Comment by frmichel** [comment]
Finally we have changed the specification to allow building a collection/container across multiple iterations. That solves the pb mentioned above, and in turn makes RML fields a viable solution for the use case described.

So there is no more need for changing the iterator inside an term map.
