### ISSUE TITLE
rr:column Vs rml:reference --> R2RML Vs RML extension

### ISSUE THREAD

**Issue by andimou** [kg-construct/collection-containers-spec#11]
I'm wondering if the collection-containers specification extends RML or R2RML. I see that `rr:column` is used so it gives me the impression that it extends R2RML but could we phrase it in a way that covers both?

**Comment by frmichel** [comment]
The examples are with rr:column because these were initially written for RDBs. But that works the same way with rml:reference.

Using rr:column in RML is valid, right? We can update the examples to avoid any confusion if you like.

**Comment by andimou** [comment]
It is indeed valid to use `rr:column` with RML but it is not the most common so it might indeed cause confusion. But besides confusion, it might make sense to say already from the beginning that this can be an extension of R2RML if the references are limited to `rr:column` so we don't limit it to RML only.

**Comment by frmichel** [comment]
Ok Christophe and I will discuss that and update the spec. We'll let you know.

**Comment by andimou** [comment]
_thinking loud_: perhaps have at each moment an example for both RML and R2RML

**Comment by andimou** [comment]
we (@anaigmo and @andimou) think that was discussed during a call, we will stick to `rml:reference`

**Comment by dachafra** [comment]
The specs uses `rml:reference` and have a comment w.r.t. the use of `rr:column`. We can close the issue

**Comment by chrdebru** [comment]
More examples are doable, but we should avoid that RML examples are only
applied to non-RDB sources. Another "elegant" solution could be to provide
one example with rr:column and put a disclaimer that while valid for RDBs,
the remainder of the document will use rml:reference.
