### ISSUE TITLE
empty values collection-containers Vs core spec

### ISSUE THREAD

**Issue by andimou** [kg-construct/collection-containers-spec#12]
I think we had this discussion in the past but I'd like to bring it up again. I see in this spec that we have `rml:allowEmptyListAndContainer`. Does this refer to an empty list or container or o an empty cell/element/object in the list? If the former should we clarify? if the latter shouldn't we use the same property as for the core specification? i.e. all term maps handled in the same way e.g., `rml:allowEmpty`.

**Comment by chrdebru** [comment]
It refers to the former, yes. If a term map yields no elements for the list or container, then no list or container is created by default. This supports those cases where one wants to generate an empty one. We could add a toy example with prime factors where the list of prime factors of the number 1 is empty. Would that clarify the example?

**Comment by frmichel** [comment]
Good point about the rml:allowEmpty, if there is no restriction on the specification of this property, then we should probably reuse it instead of rml:allowEmptyListAndContainer.

**Comment by chrdebru** [comment]
@andimou Do you have a reference to the `rml:allowEmpty`? Upon discussion, we agreed it's the former and hence different from `rml:allowEmpty`. As to avoid a predicate with a double usage/interpretation, we will currently leave it as is. That said, we could come up with a shorter predicate name.

**Comment by frmichel** [comment]
Community agreed to close this issue during Sept. 12th call.
