### ISSUE TITLE
namespace rml or other?

### ISSUE THREAD

**Issue by andimou** [kg-construct/collection-containers-spec#13]
In the case of the source/target spec, we use a different namespace, but here we still use `rml`. What would be the best strategy? I leave it as a comment here but whatever w decide should hold for all specs.

**Comment by chrdebru** [comment]
So if someone were to use RML with functions, collections, and specify
targets and sources, they end up using four namespaces?

**Comment by andimou** [comment]
I think we discussed in a call that we use rml as the namespace everywhere and we decide on a later moment if we use different namespaces.

**Comment by dachafra** [comment]
The spec is using the `rml` namespace, so we can close this issue.
