### ISSUE TITLE
Limiting the use of rr:column in the documentation.

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/collection-containers-spec#14]
Add a note about `rr:column` using an example. The section should be self-contained so that it can be removed in case `rr:column` is removed from the core specification.

**Comment by chrdebru** [comment]
All occurrences of `rr:column`` have been removed, and a small section has been added in "considerations." If that section looks good to the others, we can close this issue.

**Comment by frmichel** [comment]
Good for me.
