### ISSUE TITLE
Create examples of strategies

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/collection-containers-spec#19]
Create examples about strategies using an example with names (to demonstrate the utility of a cartesian product). Also, note that the cartesian product generates multiple lists/containers; therefore, they are identified by iteration + some "sentinel value."

**Comment by frmichel** [comment]
Decided in meeting: move rml:Strategy class to rml-core, and keep the definitions of the instances (append and cartesian product) in the container-collection spec.

**Comment by frmichel** [comment]
Create https://github.com/kg-construct/rml-core/issues/51 for the creation of the rml:Strategy class.

In collection-containers-spec we have define instances rml:Append and rml:CartesianProduct but we still need to give them a proper description.

**Comment by frmichel** [comment]
Added description for both strategies including an example.
Published.
