### ISSUE TITLE
Create example of a gather map in a predicate map

### ISSUE THREAD

**Issue by chrdebru** [kg-construct/collection-containers-spec#20]
While we have not yet come up with an example, nothing would prevent us from generating the following:

```
:a :b :c .

:b a rdf:Bag ;
    rdf:_1 :foo ;
    rdf:_2 :bar .
```

And the same for lists where the IRI is the predicate is also the IRI of the first cons-pair. Should we add an example to demonstrate this possibility?

**Comment by frmichel** [comment]
I think we take the risk of inserting quite some confusion with such an example.
Instead, I'd better add a subsection in Considerations, explaining our choice of not forbidding this use case.
By contrast I see more room for an example of a list as a subject (issue #16).

**Comment by frmichel** [comment]
Added a subsection in Considerations.
@chrdebru, feel free to reopen it if you feel that's not ok.
