### ISSUE TITLE
Building collections/containers in multiple iterations lead to ill-formed collections/containers?

### ISSUE THREAD

**Issue by frmichel** [kg-construct/collection-containers-spec#28]
@andimou @chrdebru @dachafra @pmaria, here is a summary of what I tried to explain during the call.

In the [current specification](https://kg-construct.github.io/collection-containers-spec/#valid-rdf-and-well-formedness-of-collections-and-containers), we have assumed that creating a list/container through two separate iterations would yield property rdf:firt/rdf:_1 twice, leading to an ill-formed collection/container. The given example generates this
```
_:b0    rdf:first   1 , 3 ;
        rdf:rest    ( 2 ) ;
        rdf:rest    ( 4 ) .
```
whereas we were willing to generate this:
```
_:b0    rdf:first   1 ;
        rdf:rest    ( 2, 3, 4 ) .
```
        
Nevertheless, I wonder whether this is a **conceptual issue** or just an **implementation issue.** For now, I'd favor the latter: I think this is a question about how the RDF library that is being used will behave.

If so, instead of assuming that the implementation will behave wrongly, the specification could simply state what must be the right behavior: whenever, during an iteration, we create a collection/container that happens to already exists (the head node IRI or BN id already exists), then the processor needs to append the term(s) to the existing ones.
   - For a list, that means replacing the existing "rdf:rest rdf:nil" with "rdf:rest [ rdf:first ... ; rdf:rest rdf:nil ]."
   - For a container, that means adding a new "rdf:_n+1" terms, assuming that the currently last element is rdf:_n.

Is this feasible in terms of implementation, or am I missing a conceptual hurdle?

**Comment by pmaria** [comment]
Maybe the intent could be declared explicitly using a new `rml:Strategy`? Something like `rml:appendByCollectionId`.

**Comment by chrdebru** [comment]
As per our discussion today, we have proposed an approach to solving this issue. We provided examples of combining collections/containers across iterations (with and without cartesian products as a strategy for dealing with multivalued term maps).

Glad to see we're again combining across iterations, which would allow me to avoid outer-joins with literals for relational tables! ;-)

As discussed with @frmichel, this version only assumes an "append" approach for combining across iterations. This is up for discussion, but we could also include a separate strategy for this: `rml:combine` to combine the collections/containers across iterations. These can rely on [monoids](https://en.wikipedia.org/wiki/Monoid), which are binary associative operations with an identity element (list concatenation with the empty list is one, for example), but so are "prepend", combine-and-sort, etc.

**Comment by frmichel** [comment]
As Christophe said, the last revision of the specification (with additions today 2023-01-17) solves the problem of ill-formed container/collection.

I'll close this issue, then we can submit a now one for the question about a possible rml:combine.
