### ISSUE TITLE
null lists

### ISSUE THREAD

**Issue by andimou** [kg-construct/collection-containers-spec#3]
this question was raised by @chrdebru 

how do we handle the generation of null lists?

this issue might be related to kg-construct/rml-fno-spec#16

**Comment by chrdebru** [comment]
The spec now added information and examples on how to deal with empty lists. Empty containers are easier. 

1) I have added a small note on empty lists when they are identified with an IRI or blank node identifier (they should be replaced with rdf:nil).
2) Should I add examples of those with containers?

**Comment by frmichel** [comment]
Guess the examples you added are illustrative enough.

**Comment by frmichel** [comment]
Addressed in the current spec.
