### ISSUE TITLE
do we want / can we generate collections & containers in the place of the subject map?

### ISSUE THREAD

**Issue by andimou** [kg-construct/collection-containers-spec#4]

**Comment by frmichel** [comment]
Old question but we've not answered explicitly I guess.

A term map that generates a list/container basically generates a graph with one specific node that is the head of the list/container. Technically, I think it could be possible to generate a list from a subject or predicate map. 

In the predicate case, that would probably seem very awkward: generating a list whose head node would be used as a predicate. Awkward yes, yet should be forbid it?

In the subject case, the generated subject would be the head node of the list/container, and subsequent predicate-object maps would state things about that head node. In the example below, I create a list, and at the same time I add provenance information about that list. 

```
  rr:subjectMap [
    rr:template "list/{id}" ;
    rml:gather ( [ rml:reference "values.*" ; ] ) ;
    rml:gatherAs rdf:List ;
  ] ;
  rr:predicateObjectMap [
    rr:predicate prov:wasGeneratedBy ;
    rr:object <some_activity> ;
  ] ;
```

So, in the end, I don't see why we should forbid those use cases. It would add an exception whereas we could simply state that gather maps can work with any of subject/predicate/object map.

**Comment by frmichel** [comment]
@chrdebru @dachafra @andimou what do you guys think of my explanation above?

My position would be: let's have a little exceptions, restrictions or special cases as possible. 
In other words, if there is no clear hurdle that makes something impossible or invalid, then let's make it possible. 
So I'd say let's not say anything about this question in the specification. Which "silently" allows a collection/container as a subject, and even as a predicate even though I can't figure out a use case for that.
