### ISSUE TITLE
Remove or update the goatcounter.com URL

### ISSUE THREAD

**Issue by DylanVanAssche** [kg-construct/collection-containers-spec#7]
This spec is copied from the Target one, but keeps the goatcounter URL in the `dev.html` to count visitors.

https://github.com/kg-construct/collection-containers-spec/blob/main/dev.html#L209

Goatcounter is a privacy safe alternative for Google Analytics.
Please update the URL otherwise the visitor counter will be wrong soon :)

**Comment by dachafra** [comment]
done
