### ISSUE TITLE
Deploy on Github Pages

### ISSUE THREAD

**Issue by DylanVanAssche** [kg-construct/collection-containers-spec#9]
1. Settings > Pages > Deploy from docs folder
2. Make a rendered version in the docs folder

**Comment by dachafra** [comment]
I would suggest to wait until we have a version for the deployment

**Comment by chrdebru** [comment]
Can I close this (non-)issue?

**Comment by frmichel** [comment]
@DylanVanAssche and @dachafra I have troubles generating the index.html. Wrote something in slack. Let me know.

**Comment by frmichel** [comment]
FYI, I actvated the Github pages and I submitted a PR to w3id to have a redirect from https://w3id.org/kg-construct/collections-containers.

**Comment by dachafra** [comment]
this is done
